export const program = [
	{
		weekIndex: 1,
	},
	{
		title: 'LEGS 1',
		day: 'Måndag',
		path: '/program/week-1/legs-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 1',
		day: 'Tisdag',
		path: '/program/week-1/push-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 1',
		day: 'Onsdag',
		path: '/program/week-1/pull-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'VILA',
		day: 'Torsdag',
		path: '/program/week-1/pull-1',
	},
	{
		title: 'LEGS 2',
		day: 'Fredag',
		path: '/program/week-1/legs-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 2',
		day: 'Lördag',
		path: '/program/week-1/push-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 2',
		day: 'Söndag',
		path: '/program/week-1/pull-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		weekIndex: 2,
	},
	{
		title: 'LEGS 1',
		day: 'Måndag',
		path: '/program/week-2/legs-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 1',
		day: 'Tisdag',
		path: '/program/week-2/push-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 1',
		day: 'Onsdag',
		path: '/program/week-2/pull-1',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'VILA',
		day: 'Torsdag',
		path: '/program/week-2/pull-1',
	},
	{
		title: 'LEGS 2',
		day: 'Fredag',
		path: '/program/week-2/legs-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 2',
		day: 'Lördag',
		path: '/program/week-2/push-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 2',
		day: 'Söndag',
		path: '/program/week-2/pull-2',
		exercises: 5,
		sets: 16,
		reps: 160,
	},
];
