import { exerciseNameToPath, exercises } from '.';

const e = exercises.chest;

export const program = [
	{
		weekIndex: 1,
	},
	{
		title: 'LEGS 1',
		week: 1,
		day: 'Måndag',
		path: '/program/week-1/legs-1',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 1',
		day: 'Tisdag',
		path: '/program/week-1/push-1',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 6,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 1',
		day: 'Onsdag',
		path: '/program/week-1/pull-1',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'VILA',
		day: 'Torsdag',
	},
	{
		title: 'LEGS 2',
		day: 'Fredag',
		path: '/program/week-1/legs-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 2',
		day: 'Lördag',
		path: '/program/week-1/push-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 2',
		day: 'Söndag',
		path: '/program/week-1/pull-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		weekIndex: 2,
	},
	{
		title: 'LEGS 1',
		day: 'Måndag',
		path: '/program/week-2/legs-1',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 1',
		day: 'Tisdag',
		path: '/program/week-2/push-1',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 1',
		day: 'Onsdag',
		path: '/program/week-2/pull-1',

		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'VILA',
		day: 'Torsdag',
		path: '/program/week-2/pull-1',
	},
	{
		title: 'LEGS 2',
		day: 'Fredag',
		path: '/program/week-2/legs-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PUSH 2',
		day: 'Lördag',
		path: '/program/week-2/push-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
	{
		title: 'PULL 2',
		day: 'Söndag',
		path: '/program/week-2/pull-2',
		exercises: [
			{
				name: e.INCLINE_DUMBBELL_PRESS.name,
				sets: 4,
				repsMin: 8,
				repsMax: 12,
				tracked: true,
				path: exerciseNameToPath(e.INCLINE_DUMBBELL_PRESS.name),
			},
			{
				name: e.FLAT_MACHINE_PRESS.name,
				sets: 4,
				repsMin: 10,
				repsMax: 15,
				tracked: true,
				path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
			},
			{
				name: e.SEATED_CABLE_FLY.name,
				sets: 3,
				repsMin: 10,
				repsMax: 20,
				tracked: false,
				path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
			},
			{
				first: {
					name: e.SEATED_CABLE_FLY.name,
					sets: 3,
					repsMin: 10,
					repsMax: 20,
					tracked: false,
					path: exerciseNameToPath(e.SEATED_CABLE_FLY.name),
				},
				second: {
					name: e.FLAT_MACHINE_PRESS.name,
					sets: 3,
					repsMin: 8,
					repsMax: 12,
					tracked: false,
					path: exerciseNameToPath(e.FLAT_MACHINE_PRESS.name),
				},
			},
		],
		sets: 16,
		reps: 160,
	},
];
